# encoding: utf-8
import json

# Full teachers list from user XML
TEACHERS = [
    {"id": "4874", "name": "HİDAYET AS", "short": "AS", "color": "#7ec15f"},
    {"id": "4875", "name": "HARUN BARIŞ TAHTACI", "short": "HBT", "color": "#7e5ff8"},
    {"id": "4876", "name": "BAHADIR ŞAFAK KUMCU", "short": "BŞK", "color": "#81d3ee"},
    {"id": "4878", "name": "ÇİSEM ALTINOVA", "short": "ÇİSEM", "color": "#d7b21e"},
    {"id": "4879", "name": "YEŞİM BİÇER", "short": "YEŞİM", "color": "#7ddb84"},
    {"id": "4880", "name": "NURÇİN BÜYÜKYAKALI", "short": "NURÇİ", "color": "#ee3ba2"},
    {"id": "4881", "name": "ŞEBNEM CİVAŞ", "short": "CİVAŞ", "color": "#8be18c"},
    {"id": "4882", "name": "ŞEREF ÖZCAN", "short": "ŞEREF", "color": "#b88a91"},
    {"id": "4883", "name": "ÖZGE KÜÇÜKDEMİR", "short": "ÖZGE", "color": "#beee72"},
    {"id": "4884", "name": "SEMRA IŞIKLAR", "short": "SEMRA", "color": "#0ff884"},
    {"id": "4885", "name": "HİLMİ PALA", "short": "PALA", "color": "#e3fe18"},
    {"id": "4886", "name": "YELİZ TUNÇ", "short": "YELİZ", "color": "#b148c3"},
    {"id": "4887", "name": "BİLAL AKAR", "short": "BİLAL", "color": "#2c72b2"},
    {"id": "4888", "name": "EMEL AYDIN", "short": "EMEL", "color": "#d6695e"},
    {"id": "4889", "name": "BÜŞRA SELCEN SERDAROĞLU", "short": "SELCEN", "color": "#76495d"},
    {"id": "4890", "name": "NAGİHAN ÇİÇEN", "short": "ÇİÇEN", "color": "#cb98ec"},
    {"id": "4891", "name": "AYŞE GÜL DEMİR", "short": "AYŞE", "color": "#58d55d"},
    {"id": "4892", "name": "ALPER KAYA", "short": "ALPER", "color": "#74ec74"},
    {"id": "4893", "name": "SİBEL ÜLKER", "short": "ÜLKER", "color": "#94a6e3"},
    {"id": "4894", "name": "OYA KIZILARSLAN", "short": "OYA", "color": "#b81c2f"},
    {"id": "4895", "name": "DERYA ERTUĞRUL", "short": "DERYA", "color": "#4e7be0"},
    {"id": "4896", "name": "ÖZNUR KANAL", "short": "ÖZNUR", "color": "#2a59f5"},
    {"id": "4897", "name": "ORHAN BÜYÜKYILMAZ", "short": "ORHAN", "color": "#0be9e9"},
    {"id": "4898", "name": "GÜLSEREN DEMİR", "short": "GÜLSEREN", "color": "#ac0fe7"},
    {"id": "4899", "name": "FUNDA GÜNER", "short": "FUNDA", "color": "#3cb2f9"},
    {"id": "4900", "name": "MEHMET ABUY", "short": "ABUY", "color": "#33ca5e"},
    {"id": "4901", "name": "PINAR BAYKUL", "short": "PINAR", "color": "#c45bb2"},
    {"id": "4902", "name": "ERNUR YAMAN", "short": "ERNUR", "color": "#5f7cb0"},
    {"id": "4903", "name": "SİBEL AĞGÜL", "short": "AĞGÜL", "color": "#76ea51"},
    {"id": "4904", "name": "AYSEL GÜNDÜZ", "short": "AYSEL", "color": "#df392c"},
    {"id": "4905", "name": "ZAFER KALKAN", "short": "ZAFER", "color": "#e9f939"},
    {"id": "4906", "name": "MELEK ÖZTÜRK", "short": "MELEK", "color": "#2e7a4b"},
    {"id": "4907", "name": "ZEYNEP GÜVEN", "short": "ZEYNEP", "color": "#ea7d34"},
    {"id": "4908", "name": "SADIK ÇELİK", "short": "SADIK", "color": "#3bdff8"},
    {"id": "4909", "name": "KADER MALLI", "short": "KADER", "color": "#63f253"},
    {"id": "4910", "name": "NAHİDE CANAN ŞUMNU", "short": "CANAN", "color": "#6fe60b"},
    {"id": "4911", "name": "ALPTEKİN BAŞTÜRK", "short": "ALPTE", "color": "#1edfdc"},
    {"id": "4912", "name": "SERTER IŞIKLAR", "short": "SERTE", "color": "#8195a9"},
    {"id": "4913", "name": "SEVGİ KIRMACI", "short": "SEVGİ", "color": "#ebf00e"},
    {"id": "4919", "name": "FADİME CANDAN LAZUT", "short": "FADİME", "color": "#68835f"},
    {"id": "1563", "name": "BİRCAN ÖZTRAK", "short": "BİRÖZ", "color": "#57cbb4"}
]

# Full classes list
CLASSES = [
    {"id": "1", "name": "5A", "short": "5A", "color": "#2ff2e8"},
    {"id": "2", "name": "5B", "short": "5B", "color": "#ee3518"},
    {"id": "3", "name": "5C", "short": "5C", "color": "#6ef921"},
    {"id": "4", "name": "5D", "short": "5D", "color": "#63897f"},
    {"id": "5", "name": "5E", "short": "5E", "color": "#dcfa72"},
    {"id": "6", "name": "5F", "short": "5F", "color": "#cbbce3"},
    {"id": "7", "name": "6A", "short": "6A", "color": "#cb98ec"},
    {"id": "8", "name": "6B", "short": "6B", "color": "#f06db9"},
    {"id": "9", "name": "6C", "short": "6C", "color": "#5dfcf4"},
    {"id": "10", "name": "6D", "short": "6D", "color": "#cf606c"},
    {"id": "11", "name": "6E", "short": "6E", "color": "#c2c77d"},
    {"id": "12", "name": "6F", "short": "6F", "color": "#2c6c09"},
    {"id": "13", "name": "7A", "short": "7A", "color": "#8d4ed0"},
    {"id": "14", "name": "7B", "short": "7B", "color": "#17d834"},
    {"id": "15", "name": "7C", "short": "7C", "color": "#3eaef0"},
    {"id": "16", "name": "7D", "short": "7D", "color": "#d6695e"},
    {"id": "17", "name": "7E", "short": "7E", "color": "#ecbe0d"},
    {"id": "18", "name": "7F", "short": "7F", "color": "#422894"},
    {"id": "19", "name": "8A", "short": "8A", "color": "#0ff884"},
    {"id": "20", "name": "8B", "short": "8B", "color": "#ebf00e"},
    {"id": "21", "name": "8C", "short": "8C", "color": "#4ae7e7"},
    {"id": "22", "name": "8D", "short": "8D", "color": "#6dbce5"},
    {"id": "23", "name": "8-1 DYK", "short": "8-1", "color": "#a8163f"},
    {"id": "24", "name": "8-2 DYK", "short": "8-2", "color": "#63f253"},
    {"id": "25", "name": "8-3 DYK", "short": "8-3", "color": "#0b4fe6"},
    {"id": "26", "name": "8-4 DYK", "short": "8-4", "color": "#d2eb4b"},
    {"id": "27", "name": "DESTEK EĞİTİM", "short": "DES", "color": "#1af354"},
    {"id": "28", "name": "5-1 GRUP", "short": "5-1", "color": "#eb7d34"},
    {"id": "29", "name": "5-2 GRUP", "short": "5-2", "color": "#76495d"},
    {"id": "30", "name": "6-1 GRUP", "short": "6-1", "color": "#5dfcf4"},
    {"id": "31", "name": "6-2 GRUP", "short": "6-2", "color": "#3bdff8"}
]

# Full subjects list
SUBJECTS = [
    {"id": "1", "name": "TÜRKÇE", "short": "TÜRK", "color": "#7ec15f"},
    {"id": "2", "name": "MATEMATİK", "short": "MAT", "color": "#7e5ff8"},
    {"id": "3", "name": "FEN BİLİMLERİ", "short": "FEN", "color": "#81d3ee"},
    {"id": "4", "name": "T.C. İNKILAP TARİHİ VE ATATÜRKÇÜLÜK", "short": "İNK", "color": "#8be18c"},
    {"id": "5", "name": "SOSYAL BİLGİLER", "short": "SOS", "color": "#d7b21e"},
    {"id": "6", "name": "YABANCI DİL ETKİNLİK", "short": "ETKİNLİK", "color": "#7ddb84"},
    {"id": "7", "name": "İNGİLİZCE", "short": "İNG", "color": "#ee3ba2"},
    {"id": "8", "name": "DİN KÜLTÜRÜ VE AHLAK BİLGİSİ", "short": "DKAB", "color": "#b88a91"},
    {"id": "9", "name": "GÖRSEL SANATLAR", "short": "SANAT", "color": "#beee72"},
    {"id": "10", "name": "BEDEN EĞİTİMİ VE SPOR", "short": "BEDEN", "color": "#0ff884"},
    {"id": "11", "name": "MÜZİK", "short": "MÜZİK", "color": "#e3fe18"},
    {"id": "12", "name": "BİLİŞİM TEKNOLOJİLERİ VE YAZILIM", "short": "BİLG", "color": "#b148c3"},
    {"id": "13", "name": "TEKNOLOJİ VE TASARIM", "short": "TEKNO", "color": "#2c72b2"},
    {"id": "14", "name": "REHBERLİK VE YÖNLENDİRME", "short": "REHBE", "color": "#d6695e"},
    {"id": "15", "name": "SEÇMELİ OKUMA BECERİLERİ", "short": "OKUMA", "color": "#76495d"},
    {"id": "16", "name": "SEÇMELİ MATEMATİK VE BİLİM UYGULAMALARI", "short": "BİLİM", "color": "#cb98ec"},
    {"id": "17", "name": "SEÇMELİ GÖRGÜ KURALLARI VE NEZAKET", "short": "GÖRGÜ", "color": "#58d55d"},
    {"id": "18", "name": "SEÇMELİ AHLAK VE YURTTAŞLIK EĞİTİMİ", "short": "AHLAK", "color": "#74ec74"},
    {"id": "19", "name": "SEÇMELİ YABANCI DİL", "short": "SEÇİNG", "color": "#94a6e3"},
    {"id": "20", "name": "SEÇMELİ SPOR VE FİZİKİ ETKİNLİKLER", "short": "SPOR", "color": "#b81c2f"},
    {"id": "21", "name": "SEÇMELİ YAZARLIK VE YAZMA BECERİLERİ", "short": "YAZAR", "color": "#4e7be0"},
    {"id": "22", "name": "SEÇMELİ TEMEL DİNİ BİLGİLER", "short": "TEMELDİN", "color": "#2a59f5"},
    {"id": "23", "name": "SEÇMELİ PEYGAMBERİMİZİN HAYATI", "short": "SİYER", "color": "#0be9e9"},
    {"id": "24", "name": "SEÇMELİ HUKUK VE ADALET", "short": "HUKUK", "color": "#ac0fe7"},
    {"id": "25", "name": "SEÇMELİ OYUN VE OYUN ETKİNLİKLERİ", "short": "OYUN", "color": "#3cb2f9"},
    {"id": "26", "name": "SEÇMELİ ÇEVRE VE İKLİM DEĞİŞİKLİĞİ", "short": "ÇEVRE", "color": "#33ca5e"},
    {"id": "27", "name": "SEÇMELİ KÜLTÜR VE MEDENİYETİMİZE YÖN VERENLER", "short": "KÜLTÜR", "color": "#c45bb2"},
    {"id": "28", "name": "DESTEK EĞİTİM", "short": "DESEĞ", "color": "#5f7cb0"},
    {"id": "29", "name": "DYK", "short": "DYK", "color": "#76ea51"}
]

print("Lists defined successfully")
